---
version: '3.3'
services:
  server:
    image: consul:0.9.3
    network_mode: host
    command: "consul agent -config-file /consul/config/config.json"
    ports:
      - target: 8500
        published: 8500
        mode: host
    volumes:
      - /root/techwood/crawler/infra/consul/config:/consul/config
      - /root/techwood/crawler/infra/consul/data:/consul/data
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
